[package]
name = "leet-code"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "first"
path = "1.rs"
[[bin]]
name = "second"
path = "2.rs"
[[bin]]
name = "string-to-int"
path = "8.rs"
[[bin]]
name = "palindrome"
path = "9.rs"
[[bin]]
name = "int-to-roman"
path = "12.rs"
[[bin]]
name = "longest-prefix"
path = "14.rs"
[[bin]]
name = "letter-combination"
path = "17.rs"
[[bin]]
name = "combination-sum"
path = "40.rs"
[[bin]]
name = "roman"
path = "20.rs"
[[bin]]
name = "first-ocurr-string"
path = "28.rs"
[[bin]]
name = "trapped-water"
path = "407.rs"
[[bin]]
name = "complement"
path = "476.rs"
[[bin]]
name = "max-distance-array"
path = "624.rs"
[[bin]]
name = "maximum-score"
path = "1422.rs"
[[bin]]
name = "kth-factor"
path = "1492.rs"
[[bin]]
name = "highest-peak"
path = "1765.rs"
[[bin]]
name = "merge-alternately"
path = "1768.rs"
[[bin]]
name = "grid-game"
path = "2017.rs"
[[bin]]
name = "optimal-partitin-of-string"
path = "2405.rs"
[[bin]]
name = "first-col-or-row"
path = "2661.rs"
[[bin]]
name = "bitwise-xor"
path = "2683.rs"
[[bin]]
name = "string-code"
path = "3110.rs"
[[bin]]
name = "sum-var-length"
path = "3427.rs"
[[bin]]
name = "zig-zag"
path = "zig-zag.rs"
[[bin]]
name = "min-max-sum"
path = "min_max_sum.rs"



[[bin]]
name = "bubble"
path = "bubble-sort.rs"
